version: "3"

services:
    # Database
    mysql:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_DATABASE: laravel_crud
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        networks:
            - laravel-redis

    # phpmyadmin
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: myuser
            PMA_PASSWORD: mypassword
            MYSQL_ROOT_PASSWORD: mypassword
        networks:
            - laravel-redis

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        command:
            [
                "redis-server",
                "--appendonly",
                "yes",
                "--appendfilename",
                "appendonly.aof",
                "--dir",
                "/data",
            ]
        volumes:
            - redisdata:/data
        restart: unless-stopped
        networks:
            - laravel-redis

    laravel:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.laravel
        container_name: laravel
        ports:
            - "8000:8000"
        networks:
            - laravel-redis
        environment:
            - DB_PORT=3306
            - REDIS_PORT=6379
        depends_on:
            - mysql
            - redis

    vite:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.vite
        container_name: vite
        ports:
            - "5173:5173"
        networks:
            - laravel-redis
        environment:
            - DB_PORT=3306
            - REDIS_PORT=6379
        depends_on:
            - mysql
            - redis

networks:
    laravel-redis:

volumes:
    db_data:
    redisdata:
