version: "3"

services:
    # Database
    mysql:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_DATABASE: laravel_crud
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        networks:
            - mysql-phpmyadmin-cache

    # phpmyadmin
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: myuser
            PMA_PASSWORD: mypassword
            MYSQL_ROOT_PASSWORD: mypassword
        networks:
            - mysql-phpmyadmin-cache

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        command:
            [
                "redis-server",
                "--appendonly",
                "yes",
                "--appendfilename",
                "appendonly.aof",
                "--dir",
                "/data",
            ]
        volumes:
            - redisdata:/data
        restart: unless-stopped
        networks:
            - mysql-phpmyadmin-cache

networks:
    mysql-phpmyadmin-cache:

volumes:
    db_data:
    redisdata:
