openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: This is my API's documentation
  termsOfService: <https://example.com/terms>
  contact:
    name: John Doe
    email: john.doe@example.com
    url: <https://example.com/contact>
  license:
    name: Apache 2.0
    url: <https://www.apache.org/licenses/LICENSE-2.0.html>
servers:
  - url: <https://api.example.com/v1>
paths:
  /users:
    get:
      summary: Get a list of users
      security: [{ "bearerAuth": [] }]
      tags: [User]
      responses:
        "200":
          description: Users list retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email
